### ISSUE TITLE
Interressed by your work.

### ISSUE THREAD

**Issue by xbeaudouin** [FilipDem/Domoticz-iROBOT-ROOMBA-plugin#1]
Hi,
I am interessed by your plugin. And maybe able to contribute...

Kind regards

**Comment by FilipDem** [comment]
OK, will do... Normally code is already running some months at my side.
Will have some work to document the integration (need a MQTT, so will need to document how I did it so that people can do it smoothly.
Will not be done on a very short time, but will do it the next weeks.
So if you follow, this topic, you will get notified once done.

**Comment by FilipDem** [comment]
Plugin is now working since some months without any problems integrated in Domoticz on a Raspberry Pi.
All is upload and the procedure is written... Because the procedure is written afterwards, I hope I well documented all the steps. Would you have some remarks or see some errors, let me know...
When you are happy about the work and could spend a small donation, don't hesitate... I make several plugins an have the systematically made available for the Domoticz community. I invest quite some time in it.
